fix: #3574207 Incompatibility with Commerce 3.3.x and possibly with other modules
By: interdruper
By: andyg5000
By: mogtofu33

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,5 +1,3 @@
-variables:
-  _CSPELL_IGNORE_PATHS: '**/build/icon.js, *.json, **/*.svg'
 
 include:
   - project: $_GITLAB_TEMPLATES_REPO
@@ -9,20 +7,22 @@ include:
       - "/includes/include.drupalci.variables.yml"
       - "/includes/include.drupalci.workflows.yml"
 
+variables:
+  SKIP_PHPMD:
+    value: '0'
+    description: 'Set to 1 to skip the PHPMD CI job'
+
+cspell:
+  allow_failure: true
+  variables:
+    _CSPELL_IGNORE_PATHS: '**/build/icon.js, *.json, **/*.svg'
+
 .skip-phpmd-rule: &skip-phpmd-rule
   if: '$SKIP_PHPMD == "1"'
   when: never
 
-.skip-coverage-rule: &skip-coverage-rule
-  if: '$SKIP_COVERAGE == "1"'
-  when: never
-
 .phpmd-base:
   stage: validate
-  rules:
-    - !reference [.opt-in-current-rule]
-    - *skip-phpmd-rule
-    - !reference [.php-files-exist-rule]
   needs:
     - composer
   before_script:
@@ -31,20 +31,23 @@ include:
   script:
     - php --version
     - vendor/bin/phpmd --version
-    - sed -i "s#/builds/project/ui_icons#${CI_PROJECT_DIR}#g" ${_WEB_ROOT}/modules/custom/${CI_PROJECT_NAME}/.phpmd.baseline.xml
-    - vendor/bin/phpmd
-        $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME
-        gitlab
-        $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME/.phpmd.xml
-        --exclude 'tests/*,**/tests/*'
-        --baseline-file $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME/.phpmd.baseline.xml > phpmd-quality-report.json || true
-    - vendor/bin/phpmd
-        $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME
-        text
-        $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME/.phpmd.xml
-        --exclude 'tests/*,**/tests/*'
-        --baseline-file $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME/.phpmd.baseline.xml
-  allow_failure: true
+    - |
+      BASELINE_FILE="${_WEB_ROOT}/modules/custom/${CI_PROJECT_NAME}/.phpmd.baseline.xml"
+      PHPMD_CONFIG="${_WEB_ROOT}/modules/custom/${CI_PROJECT_NAME}/.phpmd.xml"
+      if [ -f "$BASELINE_FILE" ]; then
+        sed -i "s#/builds/project/display_builder#${CI_PROJECT_DIR}#g" "$BASELINE_FILE"
+      fi
+      if [ -f "$PHPMD_CONFIG" ]; then
+        BASELINE_ARG=""
+        if [ -f "$BASELINE_FILE" ]; then
+          BASELINE_ARG="--baseline-file $BASELINE_FILE"
+        fi
+        vendor/bin/phpmd "${_WEB_ROOT}/modules/custom/${CI_PROJECT_NAME}" gitlab "$PHPMD_CONFIG" --exclude 'tests/*,**/tests/*' $BASELINE_ARG > phpmd-quality-report.json || true
+        vendor/bin/phpmd "${_WEB_ROOT}/modules/custom/${CI_PROJECT_NAME}" text "$PHPMD_CONFIG" --exclude 'tests/*,**/tests/*' $BASELINE_ARG
+      else
+        echo "[Notice] File .phpmd.xml not found at ${PHPMD_CONFIG}, skipping phpmd."
+      fi
+  allow_failure: false
   artifacts:
     expose_as: phpmd
     when: always
@@ -57,29 +60,3 @@ include:
 
 phpmd:
   extends: .phpmd-base
-
-# Coverage seems slow and not manual.
-.coverage:
-  extends:
-    - .phpunit-base
-  services:
-    - !reference [.with-database]
-  rules:
-    - !reference [.opt-in-current-rule]
-    - *skip-coverage-rule
-    - !reference [.phpunit-tests-exist-rule]
-  before_script:
-    - echo -e "\e[0Ksection_start:`date +%s`:install_xdebug[collapsed=true]\r\e[0KInstall PHP Xdebug"
-    - apt-get update
-    - apt-get install -y --no-install-recommends $PHPIZE_DEPS
-    - pecl install xdebug && docker-php-ext-enable xdebug
-    - echo -e "\e[0Ksection_end:`date +%s`:install_xdebug\r\e[0K"
-    - export XDEBUG_MODE=coverage
-  variables:
-    SYMFONY_DEPRECATIONS_HELPER: 'disabled'
-    _PHPUNIT_TESTGROUPS: ui_icons
-    _PHPUNIT_EXTRA: --testsuite unit,kernel --strict-coverage --coverage-text --only-summary-for-coverage-text
-  # @see https://docs.gitlab.com/ee/ci/yaml/#coverage
-  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
-  allow_failure: true
-  when: manual
